### PR TITLE
Switch to xo.

### PR DESCRIPTION
**Pull request by XhmikosR**
@emedvedev not sure if you prefer this solution or not, but since I had the branch for a while I though I'd make a PR :)

### CODE REVIEW

**Comment by emedvedev** [comment]
Ah, interesting. I have almost no experience with `xo`—do you generally prefer it over ESLint? Is there a specific reason?

**Comment by XhmikosR** [comment]
xo is using eslint behind the scenes too :) It's subjective so whatever you prefer. Both airbnb config and xo come with tons of rules so it just boils down to what one prefers.

I just had this branch around for so long (and also used it in the past to find issues) and I thought I'd make a PR for discussion.

**Comment by emedvedev** [comment]
Checked it out and it's actually pretty cool! I like the defaults. And this is just the project to play around with new things, so let's do it :)

**Comment by emedvedev** [comment]
It's marked as draft, so is there anything else you want to do as part of this PR? Introduce or change some rules?

**Comment by emedvedev** [comment]
Ah, and now it's not :)

**Pull request merged**
