### PR TITLE
Add Now v2 support

### LINKED ISSUE #73: Now v2 support
https://github.com/rauchg/slackin/issues/409#issuecomment-546393211

I don't use Now myself. BTW that's why we need #64 sorted somehow

### PR DESCRIPTION
**Pull request by emedvedev**
Fixes #73.

It almost works, but hilariously enough, my Now deployment got stuck and now I can't deploy anything else from my account.

@XhmikosR if you want, you can try deploying this branch with `now .` I'm not sure static routing works though, need to do some more debugging once the Zeit folks get my account working again. :)

### CODE REVIEW

**Comment by XhmikosR** [comment]
Can you deploy the latest npm published version somewhere temporarily, for
one two days, so that I can run some tests?

Also, can you update the demo link in readme?

BTW if you enable branch protection for master, there's an option to keep
branches up to date which will have a button you can press. Alternatively
we can add an action.

**Comment by emedvedev** [comment]
Demo link updated, branch protection enabled. :)

I think the easiest way to deploy the latest npm version would be to just roll it out locally, since that version doesn't work with Now anymore. I've tried fiddling with it, but no luck; locally everything works though.

**Comment by XhmikosR** [comment]
Shouldn't `https://slackin-extended.now.sh/iframe` work too?

**Comment by XhmikosR** [comment]
@emedvedev you could just cheery pick your Now fixes patches in a branch and temporarily deploy that maybe? It should work in theory

**Comment by emedvedev** [comment]
@XhmikosR that's what I've tried, but it didn't work, because Now requires some of the changes to the old build process and package.json to be cherry-picked, too. Tried to do that as well, but gave up after a while. :)

**Comment by XhmikosR** [comment]
Ah, well, I guess we'll live without a comparison. :/

Would be nice to have some numbers because I believe there will be a huge improvement between 1.1.11 and the next version.

**Pull request merged**
