### PR TITLE
Add morgan and errorhandler

### PR DESCRIPTION
**Pull request by XhmikosR**
Maybe I'll change the patch to just add the logger on dev and leave production as it was, i.e. no logging.

### CODE REVIEW

**Comment by emedvedev** [comment]
I think it's better to have logging in production as well :)

**Comment by XhmikosR** [comment]
Yeah, but the logger doesn't match the logger your are using. No big deal, just pointing it out.

**Comment by XhmikosR** [comment]
Let's keep this on hold for now. I'd like us to fix the other issues, and this is low priority

**Comment by sodabrew** [comment]
I'm using Pino in a project that wraps several instances of slackin-extended. I currently pass my logger into Express, and I'd like to pass the logger instance into the Slackin constructor as well.

**Pull request merged**
