### PR TITLE
Change the redirect code for HTTPS to 301

### LINKED ISSUE #44: res.redirect should be permanent?
https://github.com/emedvedev/slackin-extended/blob/b0addc350b0af07ca07c8df1334bacc33e21019d/lib/index.js#L113

Shouldn't this a permanent redirect?

From https://expressjs.com/en/api.html#res.redirect:

>If not specified, status defaults to “302 “Found”.

### PR DESCRIPTION
**Pull request by emedvedev**
Fixes #44

### CODE REVIEW

**Comment by XhmikosR** [comment]
@emedvedev did you test this? I don't have such a setup, just wondering :)

**Comment by emedvedev** [comment]
Did not test this particular change, but should work—it's exactly how the docs describe it. 

I live dangerously. :D

**Comment by XhmikosR** [comment]
I know :) I was just wondering if there's any case this shouldn't be a permanent redirect. I doubt there is, but maybe we should document it

**Comment by emedvedev** [comment]
The redirect is there for the case when there should be an http->https redirect but it's not handled by a reverse proxy (it was a concern for some deployments), so semantically it should always be permanent.

**Pull request merged**
