### PR TITLE
Attemp to fix Now deployments

### PR DESCRIPTION
**Pull request by XhmikosR**
Untested since I don't use Now myself.

@steveharman: can you try this branch?

### CODE REVIEW

**Comment by steveharman** [comment]
Thanks, but getting the same error - I'm sure my roblem has something to do with this, from the error log:

```
Error: No output directory named "public" found.
04:21:47 PM | More details: https://zeit.co/docs/v2/advanced/platform/frequently-asked-questions#missing-public-directory
```

but the suggestions at https://zeit.co/docs/v2/advanced/platform/frequently-asked-questions#missing-public-directory didn't help.

**Comment by XhmikosR** [comment]
I guess we need someone to provide a PR to migrate to Now 2...

**Comment by XhmikosR** [comment]
Actually, wait, please try again. I moved the config into now.json

**Comment by steveharman** [comment]
I'm up to date with `master` but still see the same error.  It could be that your work is fine, but until I can figure out the "missing public directory" issue the situation won't improve:


```
Running "npm run build"
--
04:33:04 PM | > slackin-extended@1.1.11 build /zeit/630e7bbe
04:33:04 PM | > node-sass --output-dir public --output-style compressed --precision 6 scss/ -o assets/
04:33:04 PM | Rendering Complete, saving .css file...
04:33:04 PM | Wrote CSS to /zeit/630e7bbe/assets/main.css
04:33:04 PM | Wrote 1 CSS files to /zeit/630e7bbe/assets/
04:33:04 PM | Error: No output directory named "public" found.
04:33:04 PM | More details: https://zeit.co/docs/v2/advanced/platform/frequently-asked-questions#missing-public-directory


```

**Comment by XhmikosR** [comment]
You need to try my branch, not master

**Comment by XhmikosR** [comment]
```
git clone https://github.com/XhmikosR/slackin-extended.git -b now
```

**Comment by steveharman** [comment]
got it.  when you said "my branch" I was looking for a branch called XhmikosR   ;-)

progress...

[](➜  slackin-extended git:(master) ✗ git checkout now
Branch 'now' set up to track remote branch 'now' from 'origin'.
Switched to a new branch 'now'
➜  slackin-extended git:(now) cd ..
➜  ~ now ./slackin-extended
> WARN! You are using an old version of the Now Platform. More: https://zeit.co/docs/v2/advanced/platform/changes-in-now-2-0
> Deploying ~/slackin-extended under steveharman
> Please enter values for the following environment variables:
> SLACK_API_TOKEN xoxp-7948........
> SLACK_SUBDOMAIN mysubdomain....
> Using project slackin-extended
> Error! ENOENT: no such file or directory, lstat 'assets'
➜  ~)

**Comment by XhmikosR** [comment]
That I have no idea... Also I'm not even sure if version 1 is being used with these changes or not. But from their docs (which are for v2 BTW):

>If your project contains a package.json file with a build script, and no now.json configuration, it is expected to output its static files into a directory named public, at the root of the project, when the build script is executed.

If you could point me to another project that uses now v1, we could look at its config. Or you could try experimenting with it and submitting a patch.

Remember, I don't use Now so I'm doing this just from reading the docs

**Comment by XhmikosR** [comment]
Anyway I'm gonna close this since we need someone who actually uses Now to make the v2 switch.

**Comment by emedvedev** [comment]
All done, along with live demos for PRs :)

**Pull request closed without merging**
