### PR TITLE
Use superagent from npm.

### LINKED ISSUE #58: assets/superagent.js
Is this https://github.com/visionmedia/superagent?

It seems it's the same code, some pretty old version. If so, we shouldn't have touched the file and ignore it in linting. Instead we should use the npm dist file directly.

@emedvedev can you confirm the above?

### PR DESCRIPTION
**Pull request by XhmikosR**
**Needs testing**

Closes #58

### CODE REVIEW

**Comment by XhmikosR** [comment]
I'm pretty sure superagent.js is a browserified build of an old superagent version. It's only used once in

https://github.com/emedvedev/slackin-extended/blob/a08fb6c2964925e2e5ae386a7ee7e5f946744c8d/assets/client.js#L45-L65

Judging by the year I'd say the version was 2.x. So, now it will be https://github.com/visionmedia/superagent/releases/tag/v3.0.0, which we should be OK.

That being said we can just use XHR later and get rid of the dependency for the frontend.

But before we proceed with merging this I'd like to revert any changes we made to the file. I'll make a PR in a few.

**Comment by XhmikosR** [comment]
NVM it was easier to push it here. Just don't squash the patches :)

**Comment by XhmikosR** [comment]
@emedvedev remember not to squash this

**Comment by XhmikosR** [comment]
Actually wait, it seems superagent.js isn't found on Now with this patch. Works fine locally though.

**Comment by emedvedev** [comment]
Yup :) It also doesn't currently work with Now, trying to fix.

**Comment by XhmikosR** [comment]
There is an upstream patch for Now https://github.com/rauchg/slackin/pull/399. Maybe this helps you simplify the Now deployment.

**Comment by emedvedev** [comment]
Updated it to work with Now, too.

**Pull request merged**
