### PR TITLE
Update dependencies and flatten deps tree

### PR DESCRIPTION
**Pull request by XhmikosR**
BTW I'm getting failures on my local Windows VM

```
> slackin-extended@1.1.11 mocha C:\Users\xmr\Desktop\slackin-extended
> mocha --require ./test/setup --exit



  slackin
    POST /invite
  slackin:main Theme: light +0ms
  slackin:main Establishing connection with Slack +5ms
  slackin:slack Fetching data from Slack +0ms
  slackin:slack Slack is ready +24ms
  slackin:slack Error: No logo exists for the Slack organization. +0ms
  slackin:slack Got data from Slack: 0 online, 1 total +1ms
  slackin:invite Sent an invite to foo@example.com +0ms
      √ returns success for a successful invite (61ms)
  slackin:main Theme: light +57ms
  slackin:main Establishing connection with Slack +1ms
  slackin:slack Fetching data from Slack +24ms
  slackin:slack Slack is ready +3ms
  slackin:slack Error: No logo exists for the Slack organization. +1ms
  slackin:slack Got data from Slack: 0 online, 1 total +0ms
  slackin:invite Error sending an invite to foo@example.com: other error +17ms
      √ returns a failure for a failure message
    GET /.well-known/acme-challenge/:id
  slackin:main Theme: light +10ms
  slackin:main Establishing connection with Slack +1ms
  slackin:slack Fetching data from Slack +7ms
  slackin:slack Error: Error: Nock: No match for request {
  "method": "GET",
  "url": "https://myorg.slack.com/api/users.list?token=mytoken&limit=800&cursor=&presence=1",
  "headers": {
    "accept-encoding": "gzip, deflate",
    "user-agent": "node-superagent/3.8.3"
  }
}
    at InterceptedRequestRouter.startPlayback (C:\Users\xmr\Desktop\slackin-extended\node_modules\nock\lib\intercepted_request_router.js:294:21)
    at C:\Users\xmr\Desktop\slackin-extended\node_modules\nock\lib\intercepted_request_router.js:151:14
    at InterceptedRequestRouter.handleWrite (C:\Users\xmr\Desktop\slackin-extended\node_modules\nock\lib\intercepted_request_router.js:121:9)
    at OverriddenClientRequest.req.write (C:\Users\xmr\Desktop\slackin-extended\node_modules\nock\lib\intercepted_request_router.js:69:35)
    at InterceptedRequestRouter.handleEnd (C:\Users\xmr\Desktop\slackin-extended\node_modules\nock\lib\intercepted_request_router.js:147:11)
    at OverriddenClientRequest.req.end (C:\Users\xmr\Desktop\slackin-extended\node_modules\nock\lib\intercepted_request_router.js:70:33)
    at Request._end (C:\Users\xmr\Desktop\slackin-extended\node_modules\superagent\lib\node\index.js:1021:9)
    at Request.end (C:\Users\xmr\Desktop\slackin-extended\node_modules\superagent\lib\node\index.js:777:15)
    at C:\Users\xmr\Desktop\slackin-extended\node_modules\superagent\lib\request-base.js:238:12
    at new Promise (<anonymous>)
    at Request.then (C:\Users\xmr\Desktop\slackin-extended\node_modules\superagent\lib\request-base.js:237:31)
    at processTicksAndRejections (internal/process/task_queues.js:94:5) +4ms
(node:1780) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'status' of undefined
    at SlackData.fetchUserCount (C:\Users\xmr\Desktop\slackin-extended\lib\slack.js:86:28)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
(node:1780) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1780) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
      √ returns the contents of the letsencrypt token

  slack-invite
    .invite()
      √ succeeds when ok
      √ passes along an error message


  5 passing (106ms)

````

### CODE REVIEW

**Comment by XhmikosR** [comment]
Hmm the failures happen on this repo too, but they don't make CI fail https://github.com/emedvedev/slackin-extended/runs/383090521#step:7:62

**Comment by XhmikosR** [comment]
Seems to start after #108

**Comment by XhmikosR** [comment]
Can you also change dependabot to update both files?

**Comment by emedvedev** [comment]
All new pull requests from Dependabot will update both, yeah :)

**Comment by XhmikosR** [comment]
Perfect :) Can you also enable the repo option to delete HEAD branches? It seems there are quite a few merged ones left.

**Comment by emedvedev** [comment]
Weird, I was pretty sure it was enabled already. Done.

**Comment by XhmikosR** [comment]
And remove the merged branches and we should be good to go :)

**Pull request merged**
