### PR TITLE
Add dotenv support.

### LINKED ISSUE #52: Use dotenv package
Should make things simpler

https://github.com/motdotla/dotenv

### PR DESCRIPTION
**Pull request by XhmikosR**
Fixes #52.

Now one can use a .env file in the project root with the needed environment variables. If the environment variables are already set, they take precedence.

Opening for discussion. It does seem to work fine so far for me locally.

### CODE REVIEW

**Comment by emedvedev** [comment]
I think it's fine, README just needs to be updated.

**Comment by XhmikosR** [comment]
I don't think this is ready in the sense, should it throw? Does it throw? Can we simplify `npm start` now?

And should probably go along with #80 so that the vars are loaded in the API too and not only though the bin script.

Maybe we should do this in steps, though.

**Comment by emedvedev** [comment]
I don't think it should throw (should definitely log when something is overwritten though), but `npm start` and the bin script will have to be updated to allow launching the script without positional arguments.

**Comment by XhmikosR** [comment]
IIRC dotenv does not override any already set variables, so nothing to worry there.

**Comment by emedvedev** [comment]
I mean the reverse: when already set env variables override the ones specified in `.env`. If being explicit about it is possible, I think that might reduce confusion in some cases where people could expect `.env` to take precedence.

**Comment by XhmikosR** [comment]
https://www.npmjs.com/package/dotenv#what-happens-to-environment-variables-that-were-already-set

But I don't think we should worry about this. People should use one way not mix and match.

Let's leave this change on hold for now. I'll try to move the config in the API later today.

**Comment by emedvedev** [comment]
We should probably mention this in README, and then it's fine to merge, imo.

**Pull request merged**
