### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by XhmikosR**

### CODE REVIEW

**Comment by emedvedev** [comment]
Thanks a bunch! I'll look into Dependabot asap so that we don't have to do that anymore :)

**Comment by XhmikosR** [comment]
Yup :) But still regenerating the lock file is worth once in a while. For example in this case we save about 20 deps. It will still happen eventually, but being this is transitive dependencies it usually almost never happens.

**Comment by XhmikosR** [comment]
@emedvedev can we move with some of the PRs? They are becoming obsolete as time passes by. :/

Also, I could still use some help about #20, I'm stuck with the implementation.

**Comment by XhmikosR** [comment]
@emedvedev friendly ping? :)

**Comment by emedvedev** [comment]
Sorry, got really caught up in something. The PRs (as well as #20) are on my list, I'll try my best to get to all of them tonight or tomorrow.

**Comment by XhmikosR** [comment]
Hmm

>Workflows can't be executed on this repository. Please check your payment method or billing status.

First time I see this error.

**Comment by emedvedev** [comment]
I'm emailing support about that. Apparently some organizations have encountered this as well (ansible is a notable example), but actions for open source repos should work free of charge, so it's an issue.

**Comment by XhmikosR** [comment]
I think it has to do with your payment plan, but yeah.

BTW I kept some deps back until everything is ready (stylelint namely).

**Comment by emedvedev** [comment]
Gotta love it: the issue was resolved by switching billing from monthly ($0/month) to yearly ($0/year). <3

**Comment by XhmikosR** [comment]
Yup, that's what I wanted to mention! I had read it somewhere

**Pull request merged**
