### PR TITLE
Switch to GitHub Actions CI. 

### PR DESCRIPTION
**Pull request by XhmikosR**
I'll rebase this when the other PRs are merged and GitHub Actions are enabled for the repo.

Preview: https://github.com/XhmikosR/slackin-extended/runs/268094815

You should also enable [automated security fixes](https://help.github.com/en/articles/configuring-automated-security-fixes) @emedvedev

### CODE REVIEW

**Comment by emedvedev** [comment]
Actions are enabled now :)

**Comment by XhmikosR** [comment]
Can you enable automated security fixes too?

Note that this will fire after you merge it. And there's one lint failure that you should fix. I'd fix it but I don't get where the var is coming from.

**Comment by emedvedev** [comment]
Done

**Comment by XhmikosR** [comment]
@emedvedev can we move with this? I believe the `emailFilter` error is a real error. Also the code for `channels` is wrong hence why I hit #19.

**Comment by XhmikosR** [comment]
Now tests are green: https://github.com/XhmikosR/slackin-extended/runs/268094815

**Comment by XhmikosR** [comment]
@emedvedev can we get this merged?

**Comment by emedvedev** [comment]
Yup! Was just reviewing it and reading up on actions, sorry it took a while. :)

**Pull request merged**
